version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    depends_on:
      - db
    ports:
      - "4500:80"
    restart: always
    volumes:
      - ./api:/app
    networks:
      - bulb-site
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      #- ./db-data:/var/lib/mysql
      - ./bulbstudios.sql:/docker-entrypoint-initdb.d/bulbstudios.sql
    #ports:
    #  - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bulbstudios
      MYSQL_USER: bulbstudios_admin
      MYSQL_PASSWORD: UPWwBoxynISNm4Wa
    networks:
      - bulb-site
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bulbstudios
      MYSQL_USER: bulbstudios_admin
      MYSQL_PASSWORD: UPWwBoxynISNm4Wa
    ports:
      - "8088:80"
    networks:
      - bulb-site
networks:
  bulb-site:
volumes:
  api:
  